dist: focal
language: node_js
node_js:
  - '14.17.0'
  - '16.0.0'

os:
  - linux

cache:
  directories:
    - ./node_modules

install:
  - npm ci --no-progress

script:
  - npm run eslint:check
  - npm run prettier:check
  - npm run build
